// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'store_model_by_id.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_StoreModelById _$StoreModelByIdFromJson(Map<String, dynamic> json) =>
    _StoreModelById(
      id: (json['id'] as num?)?.toInt(),
      userId: (json['user_id'] as num?)?.toInt(),
      storeCode: json['store_code'] as String?,
      slug: json['slug'] as String?,
      storeName: json['store_name'] as String?,
      storeWebsite: json['store_website'] as String?,
      email: json['email'] as String?,
      mobile: json['mobile'] as String?,
      phone: json['phone'] as String?,
      website: json['website'] as String?,
      storeLogo: json['store_logo'] as String?,
      logo: json['logo'] as String?,
      country: json['country'] as String?,
      state: json['state'],
      city: json['city'] as String?,
      address: json['address'] as String?,
      postcode: (json['postcode'] as num?)?.toInt(),
      ifGst: json['if_gst'],
      gstNo: json['gst_no'] as String?,
      ifVat: json['if_vat'],
      vatNo: json['vat_no'] as String?,
      panNo: json['pan_no'] as String?,
      upiId: json['upi_id'] as String?,
      upiCode: json['upi_code'] as String?,
      bankDetails: json['bank_details'] as String?,
      cid: json['cid'] as String?,
      categoryInit: json['category_init'] as String?,
      itemInit: json['item_init'] as String?,
      supplierInit: json['supplier_init'] as String?,
      purchaseInit: json['purchase_init'] as String?,
      purchaseReturnInit: json['purchase_return_init'] as String?,
      customerInit: json['customer_init'] as String?,
      salesInit: json['sales_init'] as String?,
      salesReturnInit: json['sales_return_init'] as String?,
      expenseInit: json['expense_init'] as String?,
      accountsInit: json['accounts_init'] as String?,
      journalInit: json['journal_init'] as String?,
      custAdvanceInit: json['cust_advance_init'] as String?,
      quotationInit: json['quotation_init'] as String?,
      moneyTransferInit: json['money_transfer_init'] as String?,
      salesPaymentInit: json['sales_payment_init'] as String?,
      salesReturnPaymentInit: json['sales_return_payment_init'] as String?,
      purchasePaymentInit: json['purchase_payment_init'] as String?,
      purchaseReturnPaymentInit:
          json['purchase_return_payment_init'] as String?,
      expensePaymentInit: json['expense_payment_init'] as String?,
      smsStatus: (json['sms_status'] as num?)?.toInt(),
      languageId: (json['language_id'] as num?)?.toInt(),
      currencyId: json['currency_id'] as String?,
      currencyPlacement: json['currency_placement'] as String?,
      timezone: json['timezone'] as String?,
      dateFormat: json['date_format'] as String?,
      timeFormat: json['time_format'] as String?,
      defaultSalesDiscount: json['default_sales_discount'] as String?,
      currencywsymbolId: (json['currencywsymbol_id'] as num?)?.toInt(),
      regnoKey: json['regno_key'] as String?,
      favIcon: json['fav_icon'] as String?,
      purchaseCode: json['purchase_code'] as String?,
      changeReturn: (json['change_return'] as num?)?.toInt(),
      salesInvoiceFormatId: (json['sales_invoice_format_id'] as num?)?.toInt(),
      posInvoiceFormatId: (json['pos_invoice_format_id'] as num?)?.toInt(),
      salesInvoiceFooterText: json['sales_invoice_footer_text'] as String?,
      ifSerialno: (json['if_serialno'] as num?)?.toInt(),
      ifModelno: json['if_modelno'] as String?,
      ifExpiry: json['if_expiry'] as String?,
      ifBatchno: json['if_batchno'] as String?,
      roundOff: (json['round_off'] as num?)?.toInt(),
      decimals: (json['decimals'] as num?)?.toInt(),
      qtyDecimals: (json['qty_decimals'] as num?)?.toInt(),
      smtpHost: json['smtp_host'] as String?,
      smtpPort: json['smtp_port'] as String?,
      smtpUser: json['smtp_user'] as String?,
      smtpPass: json['smtp_pass'] as String?,
      smtpStatus: (json['smtp_status'] as num?)?.toInt(),
      ifOtp: (json['if_otp'] as num?)?.toInt(),
      smsUrl: json['sms_url'] as String?,
      ifMsg91: (json['if_msg91'] as num?)?.toInt(),
      msg91Apikey: json['msg91_apikey'] as String?,
      smsSenderid: json['sms_senderid'] as String?,
      smsDltid: json['sms_dltid'] as String?,
      smsMsg: json['sms_msg'] as String?,
      ifCod: (json['if_cod'] as num?)?.toInt(),
      ifPickupatestore: (json['if_pickupatestore'] as num?)?.toInt(),
      ifFixeddelivery: (json['if_fixeddelivery'] as num?)?.toInt(),
      deliveryCharge: json['delivery_charge'] as String?,
      ifHandlingcharge: (json['if_handlingcharge'] as num?)?.toInt(),
      handlingCharge: json['handling_charge'] as String?,
      signature: json['signature'] as String?,
      showSignature: (json['show_signature'] as num?)?.toInt(),
      tAndCStatus: (json['t_and_c_status'] as num?)?.toInt(),
      tAndCStatusPos: (json['t_and_c_status_pos'] as num?)?.toInt(),
      numberToWords: (json['number_to_words'] as num?)?.toInt(),
      ifExictiveapp: (json['if_exictiveapp'] as num?)?.toInt(),
      ifCustomerapp: (json['if_customerapp'] as num?)?.toInt(),
      ifDeliveryapp: (json['if_deliveryapp'] as num?)?.toInt(),
      ifOnesignal: (json['if_onesignal'] as num?)?.toInt(),
      onesignalId: json['onesignal_id'] as String?,
      onesignalKey: json['onesignal_key'] as String?,
      currentSubscriptionId: (json['current_subscription_id'] as num?)?.toInt(),
      invoiceView: json['invoice_view'] as String?,
      previousBalancebit: (json['previous_balancebit'] as num?)?.toInt(),
      defaultAccountId: (json['default_account_id'] as num?)?.toInt(),
      status: json['status'] as String?,
      createdBy: (json['created_by'] as num?)?.toInt(),
      createdAt: json['created_at'] == null
          ? null
          : DateTime.parse(json['created_at'] as String),
      updatedAt: json['updated_at'] == null
          ? null
          : DateTime.parse(json['updated_at'] as String),
    );

Map<String, dynamic> _$StoreModelByIdToJson(_StoreModelById instance) =>
    <String, dynamic>{
      'id': instance.id,
      'user_id': instance.userId,
      'store_code': instance.storeCode,
      'slug': instance.slug,
      'store_name': instance.storeName,
      'store_website': instance.storeWebsite,
      'email': instance.email,
      'mobile': instance.mobile,
      'phone': instance.phone,
      'website': instance.website,
      'store_logo': instance.storeLogo,
      'logo': instance.logo,
      'country': instance.country,
      'state': instance.state,
      'city': instance.city,
      'address': instance.address,
      'postcode': instance.postcode,
      'if_gst': instance.ifGst,
      'gst_no': instance.gstNo,
      'if_vat': instance.ifVat,
      'vat_no': instance.vatNo,
      'pan_no': instance.panNo,
      'upi_id': instance.upiId,
      'upi_code': instance.upiCode,
      'bank_details': instance.bankDetails,
      'cid': instance.cid,
      'category_init': instance.categoryInit,
      'item_init': instance.itemInit,
      'supplier_init': instance.supplierInit,
      'purchase_init': instance.purchaseInit,
      'purchase_return_init': instance.purchaseReturnInit,
      'customer_init': instance.customerInit,
      'sales_init': instance.salesInit,
      'sales_return_init': instance.salesReturnInit,
      'expense_init': instance.expenseInit,
      'accounts_init': instance.accountsInit,
      'journal_init': instance.journalInit,
      'cust_advance_init': instance.custAdvanceInit,
      'quotation_init': instance.quotationInit,
      'money_transfer_init': instance.moneyTransferInit,
      'sales_payment_init': instance.salesPaymentInit,
      'sales_return_payment_init': instance.salesReturnPaymentInit,
      'purchase_payment_init': instance.purchasePaymentInit,
      'purchase_return_payment_init': instance.purchaseReturnPaymentInit,
      'expense_payment_init': instance.expensePaymentInit,
      'sms_status': instance.smsStatus,
      'language_id': instance.languageId,
      'currency_id': instance.currencyId,
      'currency_placement': instance.currencyPlacement,
      'timezone': instance.timezone,
      'date_format': instance.dateFormat,
      'time_format': instance.timeFormat,
      'default_sales_discount': instance.defaultSalesDiscount,
      'currencywsymbol_id': instance.currencywsymbolId,
      'regno_key': instance.regnoKey,
      'fav_icon': instance.favIcon,
      'purchase_code': instance.purchaseCode,
      'change_return': instance.changeReturn,
      'sales_invoice_format_id': instance.salesInvoiceFormatId,
      'pos_invoice_format_id': instance.posInvoiceFormatId,
      'sales_invoice_footer_text': instance.salesInvoiceFooterText,
      'if_serialno': instance.ifSerialno,
      'if_modelno': instance.ifModelno,
      'if_expiry': instance.ifExpiry,
      'if_batchno': instance.ifBatchno,
      'round_off': instance.roundOff,
      'decimals': instance.decimals,
      'qty_decimals': instance.qtyDecimals,
      'smtp_host': instance.smtpHost,
      'smtp_port': instance.smtpPort,
      'smtp_user': instance.smtpUser,
      'smtp_pass': instance.smtpPass,
      'smtp_status': instance.smtpStatus,
      'if_otp': instance.ifOtp,
      'sms_url': instance.smsUrl,
      'if_msg91': instance.ifMsg91,
      'msg91_apikey': instance.msg91Apikey,
      'sms_senderid': instance.smsSenderid,
      'sms_dltid': instance.smsDltid,
      'sms_msg': instance.smsMsg,
      'if_cod': instance.ifCod,
      'if_pickupatestore': instance.ifPickupatestore,
      'if_fixeddelivery': instance.ifFixeddelivery,
      'delivery_charge': instance.deliveryCharge,
      'if_handlingcharge': instance.ifHandlingcharge,
      'handling_charge': instance.handlingCharge,
      'signature': instance.signature,
      'show_signature': instance.showSignature,
      't_and_c_status': instance.tAndCStatus,
      't_and_c_status_pos': instance.tAndCStatusPos,
      'number_to_words': instance.numberToWords,
      'if_exictiveapp': instance.ifExictiveapp,
      'if_customerapp': instance.ifCustomerapp,
      'if_deliveryapp': instance.ifDeliveryapp,
      'if_onesignal': instance.ifOnesignal,
      'onesignal_id': instance.onesignalId,
      'onesignal_key': instance.onesignalKey,
      'current_subscription_id': instance.currentSubscriptionId,
      'invoice_view': instance.invoiceView,
      'previous_balancebit': instance.previousBalancebit,
      'default_account_id': instance.defaultAccountId,
      'status': instance.status,
      'created_by': instance.createdBy,
      'created_at': instance.createdAt?.toIso8601String(),
      'updated_at': instance.updatedAt?.toIso8601String(),
    };
