import 'package:freezed_annotation/freezed_annotation.dart';

part "store_model_by_id.freezed.dart";
part "store_model_by_id.g.dart";

@freezed
abstract class StoreModelById with _$StoreModelById {
  const factory StoreModelById({
    @JsonKey(name: "id") int? id,
    @JsonKey(name: "user_id") int? userId,
    @JsonKey(name: "store_code") String? storeCode,
    @JsonKey(name: "slug") String? slug,
    @JsonKey(name: "store_name") String? storeName,
    @JsonKey(name: "store_website") String? storeWebsite,
    @JsonKey(name: "email") String? email,
    @JsonKey(name: "mobile") String? mobile,
    @JsonKey(name: "phone") String? phone,
    @JsonKey(name: "website") String? website,
    @JsonKey(name: "store_logo") String? storeLogo,
    @JsonKey(name: "logo") String? logo,
    @JsonKey(name: "country") String? country,
    @JsonKey(name: "state") dynamic state,
    @JsonKey(name: "city") String? city,
    @JsonKey(name: "address") String? address,
    @JsonKey(name: "postcode") int? postcode,
    @JsonKey(name: "if_gst") dynamic ifGst,
    @JsonKey(name: "gst_no") String? gstNo,
    @JsonKey(name: "if_vat") dynamic ifVat,
    @JsonKey(name: "vat_no") String? vatNo,
    @JsonKey(name: "pan_no") String? panNo,
    @JsonKey(name: "upi_id") String? upiId,
    @JsonKey(name: "upi_code") String? upiCode,
    @JsonKey(name: "bank_details") String? bankDetails,
    @JsonKey(name: "cid") String? cid,
    @JsonKey(name: "category_init") String? categoryInit,
    @JsonKey(name: "item_init") String? itemInit,
    @JsonKey(name: "supplier_init") String? supplierInit,
    @JsonKey(name: "purchase_init") String? purchaseInit,
    @JsonKey(name: "purchase_return_init") String? purchaseReturnInit,
    @JsonKey(name: "customer_init") String? customerInit,
    @JsonKey(name: "sales_init") String? salesInit,
    @JsonKey(name: "sales_return_init") String? salesReturnInit,
    @JsonKey(name: "expense_init") String? expenseInit,
    @JsonKey(name: "accounts_init") String? accountsInit,
    @JsonKey(name: "journal_init") String? journalInit,
    @JsonKey(name: "cust_advance_init") String? custAdvanceInit,
    @JsonKey(name: "quotation_init") String? quotationInit,
    @JsonKey(name: "money_transfer_init") String? moneyTransferInit,
    @JsonKey(name: "sales_payment_init") String? salesPaymentInit,
    @JsonKey(name: "sales_return_payment_init") String? salesReturnPaymentInit,
    @JsonKey(name: "purchase_payment_init") String? purchasePaymentInit,
    @JsonKey(name: "purchase_return_payment_init")
    String? purchaseReturnPaymentInit,
    @JsonKey(name: "expense_payment_init") String? expensePaymentInit,
    @JsonKey(name: "sms_status") int? smsStatus,
    @JsonKey(name: "language_id") int? languageId,
    @JsonKey(name: "currency_id") String? currencyId,
    @JsonKey(name: "currency_placement") String? currencyPlacement,
    @JsonKey(name: "timezone") String? timezone,
    @JsonKey(name: "date_format") String? dateFormat,
    @JsonKey(name: "time_format") String? timeFormat,
    @JsonKey(name: "default_sales_discount") String? defaultSalesDiscount,
    @JsonKey(name: "currencywsymbol_id") int? currencywsymbolId,
    @JsonKey(name: "regno_key") String? regnoKey,
    @JsonKey(name: "fav_icon") String? favIcon,
    @JsonKey(name: "purchase_code") String? purchaseCode,
    @JsonKey(name: "change_return") int? changeReturn,
    @JsonKey(name: "sales_invoice_format_id") int? salesInvoiceFormatId,
    @JsonKey(name: "pos_invoice_format_id") int? posInvoiceFormatId,
    @JsonKey(name: "sales_invoice_footer_text") String? salesInvoiceFooterText,
    @JsonKey(name: "if_serialno") int? ifSerialno,
    @JsonKey(name: "if_modelno") String? ifModelno,
    @JsonKey(name: "if_expiry") String? ifExpiry,
    @JsonKey(name: "if_batchno") String? ifBatchno,
    @JsonKey(name: "round_off") int? roundOff,
    @JsonKey(name: "decimals") int? decimals,
    @JsonKey(name: "qty_decimals") int? qtyDecimals,
    @JsonKey(name: "smtp_host") String? smtpHost,
    @JsonKey(name: "smtp_port") String? smtpPort,
    @JsonKey(name: "smtp_user") String? smtpUser,
    @JsonKey(name: "smtp_pass") String? smtpPass,
    @JsonKey(name: "smtp_status") int? smtpStatus,
    @JsonKey(name: "if_otp") int? ifOtp,
    @JsonKey(name: "sms_url") String? smsUrl,
    @JsonKey(name: "if_msg91") int? ifMsg91,
    @JsonKey(name: "msg91_apikey") String? msg91Apikey,
    @JsonKey(name: "sms_senderid") String? smsSenderid,
    @JsonKey(name: "sms_dltid") String? smsDltid,
    @JsonKey(name: "sms_msg") String? smsMsg,
    @JsonKey(name: "if_cod") int? ifCod,
    @JsonKey(name: "if_pickupatestore") int? ifPickupatestore,
    @JsonKey(name: "if_fixeddelivery") int? ifFixeddelivery,
    @JsonKey(name: "delivery_charge") String? deliveryCharge,
    @JsonKey(name: "if_handlingcharge") int? ifHandlingcharge,
    @JsonKey(name: "handling_charge") String? handlingCharge,
    @JsonKey(name: "signature") String? signature,
    @JsonKey(name: "show_signature") int? showSignature,
    @JsonKey(name: "t_and_c_status") int? tAndCStatus,
    @JsonKey(name: "t_and_c_status_pos") int? tAndCStatusPos,
    @JsonKey(name: "number_to_words") int? numberToWords,
    @JsonKey(name: "if_exictiveapp") int? ifExictiveapp,
    @JsonKey(name: "if_customerapp") int? ifCustomerapp,
    @JsonKey(name: "if_deliveryapp") int? ifDeliveryapp,
    @JsonKey(name: "if_onesignal") int? ifOnesignal,
    @JsonKey(name: "onesignal_id") String? onesignalId,
    @JsonKey(name: "onesignal_key") String? onesignalKey,
    @JsonKey(name: "current_subscription_id") int? currentSubscriptionId,
    @JsonKey(name: "invoice_view") String? invoiceView,
    @JsonKey(name: "previous_balancebit") int? previousBalancebit,
    @JsonKey(name: "default_account_id") int? defaultAccountId,
    @JsonKey(name: "status") String? status,
    @JsonKey(name: "created_by") int? createdBy,
    @JsonKey(name: "created_at") DateTime? createdAt,
    @JsonKey(name: "updated_at") DateTime? updatedAt,
  }) = _StoreModelById;
  factory StoreModelById.fromJson(Map<String, dynamic> json) =>
      _$StoreModelByIdFromJson(json);
}
