name: greenbiller
description: "A new Flutter project."
author: "xaviyo_george"


version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  fl_chart: ^0.69.0
  drop_down_list: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.3.0
  logger: ^1.4.0
  onesignal_flutter: ^5.3.4
  image_picker: ^1.2.0
  open_file: ^3.5.10
  file_picker: ^10.3.2
  csv: ^6.0.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  pdf: ^3.11.3
  barcode_widget: ^2.0.4
  barcode: ^2.2.9
  printing: ^5.14.2
  intl: ^0.20.2
  url_launcher: ^6.3.2
  editable: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.0
  flutter_lints: ^5.0.0
  analyzer: 


flutter:
  uses-material-design: true
  assets:
    - assets/images/

  